para = """This study demonstrates that the Marangoni flow in a channel network can solve maze problems such as 
exploring and visualizing the shortest path and finding all possible solutions in a parallel fashion. The Marangoni 
flow is generated by the pH gradient in a maze filled with an alkaline solution of a fatty acid by introducing a 
hydrogel block soaked with an acid at the exit. The pH gradient changes the protonation rate of fatty acid molecules, 
which translates into the surface tension gradient at the liquid–air interface through the maze. Fluid flow 
maintained by the surface tension gradient (Marangoni flow) can drag water-soluble dye particles toward low pH (exit) 
at the liquid–air interface. Dye particles placed at the entrance of the maze dissolve during this motion, 
thus exhibiting and finding the shortest path and all possible paths in a maze. """

words = para.split(' ')
unique_words = list(set(words))
words_sorted = sorted(words)

print(unique_words)
print(words_sorted)

word_count = dict.fromkeys(unique_words, 1)

for word in unique_words:
    try:
        _index = words_sorted.index(word)
        while words_sorted[_index] == words_sorted[_index + 1]:
            word_count[word] += 1
            _index += 1
    except IndexError:
        pass

print(word_count, sep='\n')
